### ISSUE TITLE
Energy Transmitter

### ISSUE THREAD

**Issue by TookUrSweetRoll** [RuochenFu21/CreateEnderTransmission#8]
Transmits power to all sides as seen in the pic. Also cannot connect it to a gearbox for the input, just pops off.

Forge- 47.1.43
create-1.20.1-0.5.1.d
createendertransmission-2.0.4-1.20.1

![2023-08-21_10 51 18](https://github.com/RuochenFu21/CreateEnderTransmission/assets/29466666/4e110c0f-b4f7-4f20-828a-e86239448c2b)

**Comment by furuochen-dev** [comment]
weird

**Comment by notnate75** [comment]
I can confirm this is happening to me too.  I am having other issues too, but will detail them elsewhere.

**Comment by Endalion** [comment]
If the energy transmitter is at default settings (empty password and channel 1), it propagates to all sides because of 

https://github.com/RuochenFu21/CreateEnderTransmission/blob/1c6f8f3b79671cb00510e5ab9d837e0b1c6bc2eb/src/main/java/com/forsteri/createendertransmission/blocks/energyTransmitter/EnergyTransmitterBlockEntity.java#L103-L107

ie. when the target block is *not* a transmitter and thus has no data, compoundTag returns `0` for channel and `""` for password, allowing the transmitter to propagate there.
